"""Audio fixture generators. spec_lines 43 (specs/cascade-a.md, AC-19).

Synthesizes numpy arrays / WAV files under ``tests/fixtures/audio/`` for
white noise, pink noise, and a clean-speech-plus-noise mix at a
caller-specified SNR (dB). These are fixture-generation utilities used by
other tests, not test assertions themselves.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import soundfile

DEFAULT_SAMPLE_RATE = 16_000
_AUDIO_DIR = Path(__file__).resolve().parent / "audio"


def white_noise(duration_s: float, sample_rate: int = DEFAULT_SAMPLE_RATE, seed: int | None = None) -> np.ndarray:
    """Gaussian white noise: flat power spectral density."""
    n_samples = int(duration_s * sample_rate)
    rng = np.random.default_rng(seed)
    return rng.standard_normal(n_samples)


def pink_noise(duration_s: float, sample_rate: int = DEFAULT_SAMPLE_RATE, seed: int | None = None) -> np.ndarray:
    """Pink (1/f) noise: power spectral density falls off as 1/frequency.

    Generated by shaping white noise in the frequency domain (amplitude
    scaled by 1/sqrt(f), giving power ~ 1/f) and transforming back to time
    domain.
    """
    n_samples = int(duration_s * sample_rate)
    if n_samples <= 0:
        return np.zeros(0, dtype=np.float64)

    rng = np.random.default_rng(seed)
    white = rng.standard_normal(n_samples)

    spectrum = np.fft.rfft(white)
    freqs = np.fft.rfftfreq(n_samples, d=1.0 / sample_rate)
    freqs[0] = freqs[1] if len(freqs) > 1 else 1.0  # avoid divide-by-zero at DC
    shaped = spectrum / np.sqrt(freqs)

    pink = np.fft.irfft(shaped, n=n_samples)
    std = np.std(pink)
    return pink / std if std > 0 else pink


def mix_at_snr(speech: np.ndarray, noise: np.ndarray, snr_db: float) -> np.ndarray:
    """Mix ``speech`` with ``noise`` scaled to the requested SNR (in dB).

    The noise is scaled so that the power ratio of speech to (scaled) noise
    equals ``10 ** (snr_db / 10)``, then added sample-for-sample. The output
    has the same length as ``speech``.
    """
    speech = np.asarray(speech, dtype=np.float64)
    noise = np.asarray(noise, dtype=np.float64)
    n = len(speech)
    if len(noise) < n:
        reps = -(-n // max(len(noise), 1))  # ceil div
        noise = np.tile(noise, reps)
    noise = noise[:n]

    speech_power = np.mean(speech ** 2)
    noise_power = np.mean(noise ** 2)
    if noise_power == 0:
        scale = 0.0
    else:
        scale = np.sqrt(speech_power / noise_power) * (10.0 ** (-snr_db / 20.0))

    return speech + noise * scale


def write_noisy_speech(
    name: str,
    speech: np.ndarray,
    snr_db: float,
    noise_kind: str = "white",
    sample_rate: int = DEFAULT_SAMPLE_RATE,
) -> str:
    """Mix ``speech`` with generated noise at ``snr_db`` and write it as a
    WAV fixture under ``tests/fixtures/audio/<name>.wav``. Returns the path.
    """
    speech = np.asarray(speech, dtype=np.float64)
    duration_s = len(speech) / sample_rate

    if noise_kind == "white":
        noise = white_noise(duration_s, sample_rate=sample_rate)
    elif noise_kind == "pink":
        noise = pink_noise(duration_s, sample_rate=sample_rate)
    else:
        raise ValueError(f"unknown noise_kind: {noise_kind!r}")

    mixed = mix_at_snr(speech, noise, snr_db)

    _AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    path = _AUDIO_DIR / f"{name}.wav"
    soundfile.write(str(path), mixed, sample_rate)
    return str(path)
